name: CI/CD Pipeline for Video Streaming System

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Services
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Upload Video Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/upload-video-service ./Upload-Video-Service
        docker push ${{ secrets.DOCKER_USERNAME }}/upload-video-service

    - name: Build and push Authentication Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service ./Authentication-Service
        docker push ${{ secrets.DOCKER_USERNAME }}/auth-service

    - name: Build and push File System Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/file-system-service ./File-System-Service
        docker push ${{ secrets.DOCKER_USERNAME }}/file-system-service

    - name: Build and push MySQL DB Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mysql-db-service ./MySQL-DB-Service
        docker push ${{ secrets.DOCKER_USERNAME }}/mysql-db-service

    - name: Build and push Stream Video Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/stream-video-service ./Stream-Video-Service
        docker push ${{ secrets.DOCKER_USERNAME }}/stream-video-service

  deploy:
    name: Deploy Services
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: SSH to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}

    - name: Pull and run Docker images
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/upload-video-service
        docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service
        docker pull ${{ secrets.DOCKER_USERNAME }}/file-system-service
        docker pull ${{ secrets.DOCKER_USERNAME }}/mysql-db-service
        docker pull ${{ secrets.DOCKER_USERNAME }}/stream-video-service
        
        
        cd /home/ec2-user2
  
        docker-compose -f docker-compose.yml up
